# Form implementation generated from reading ui file 'ui/add_workout.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_AddWorkout(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 645)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(170, 10, 231, 22))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 150, 67, 22))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(20, 270, 121, 22))
        self.label_3.setObjectName("label_3")
        self.comboBoxWorkoutType = QtWidgets.QComboBox(parent=Dialog)
        self.comboBoxWorkoutType.setGeometry(QtCore.QRect(190, 270, 251, 30))
        self.comboBoxWorkoutType.setObjectName("comboBoxWorkoutType")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(20, 400, 67, 22))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setGeometry(QtCore.QRect(20, 460, 67, 22))
        self.label_5.setObjectName("label_5")
        self.dateEdit = QtWidgets.QDateEdit(parent=Dialog)
        self.dateEdit.setGeometry(QtCore.QRect(190, 400, 131, 31))
        self.dateEdit.setObjectName("dateEdit")
        self.timeEdit = QtWidgets.QTimeEdit(parent=Dialog)
        self.timeEdit.setGeometry(QtCore.QRect(190, 460, 131, 31))
        self.timeEdit.setObjectName("timeEdit")
        self.label_6 = QtWidgets.QLabel(parent=Dialog)
        self.label_6.setGeometry(QtCore.QRect(20, 340, 67, 22))
        self.label_6.setObjectName("label_6")
        self.comboBoxTrainers = QtWidgets.QComboBox(parent=Dialog)
        self.comboBoxTrainers.setGeometry(QtCore.QRect(190, 340, 251, 30))
        self.comboBoxTrainers.setObjectName("comboBoxTrainers")
        self.addWorkoutButton = QtWidgets.QPushButton(parent=Dialog)
        self.addWorkoutButton.setGeometry(QtCore.QRect(200, 560, 91, 30))
        self.addWorkoutButton.setObjectName("addWorkoutButton")
        self.listWidget = QtWidgets.QListWidget(parent=Dialog)
        self.listWidget.setGeometry(QtCore.QRect(160, 100, 271, 131))
        self.listWidget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.NoSelection)
        self.listWidget.setObjectName("listWidget")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Тренировки"))
        self.label_2.setText(_translate("Dialog", "Клиенты"))
        self.label_3.setText(_translate("Dialog", "Тип тренировки"))
        self.label_4.setText(_translate("Dialog", "Дата"))
        self.label_5.setText(_translate("Dialog", "Время"))
        self.label_6.setText(_translate("Dialog", "Тренер"))
        self.addWorkoutButton.setText(_translate("Dialog", "Добавить"))
