# Form implementation generated from reading ui file 'ui/dialogs/workoutDetailDialog.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WorkoutDetailDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(431, 291)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(80, 10, 301, 22))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 141, 22))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 100, 67, 22))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 140, 101, 22))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 180, 67, 22))
        self.label_5.setObjectName("label_5")
        self.trainingType = QtWidgets.QLabel(parent=Dialog)
        self.trainingType.setGeometry(QtCore.QRect(180, 50, 191, 22))
        self.trainingType.setText("")
        self.trainingType.setObjectName("trainingType")
        self.dateAndTime = QtWidgets.QLabel(parent=Dialog)
        self.dateAndTime.setGeometry(QtCore.QRect(170, 140, 191, 22))
        self.dateAndTime.setText("")
        self.dateAndTime.setObjectName("dateAndTime")
        self.trainer = QtWidgets.QLabel(parent=Dialog)
        self.trainer.setGeometry(QtCore.QRect(180, 90, 191, 22))
        self.trainer.setText("")
        self.trainer.setObjectName("trainer")
        self.clients = QtWidgets.QLabel(parent=Dialog)
        self.clients.setGeometry(QtCore.QRect(160, 180, 191, 71))
        self.clients.setText("")
        self.clients.setObjectName("clients")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Информация о тренировке"))
        self.label_2.setText(_translate("Dialog", "Тип тренировки"))
        self.label_3.setText(_translate("Dialog", "Тренер"))
        self.label_4.setText(_translate("Dialog", "Дата и время"))
        self.label_5.setText(_translate("Dialog", "Клиенты"))
