# Form implementation generated from reading ui file 'addADmin.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(508, 485)
        self.addAdminLabel = QtWidgets.QLabel(parent=Dialog)
        self.addAdminLabel.setGeometry(QtCore.QRect(50, 60, 381, 22))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(16)
        self.addAdminLabel.setFont(font)
        self.addAdminLabel.setObjectName("addAdminLabel")
        self.loginEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.loginEdit.setGeometry(QtCore.QRect(180, 260, 171, 30))
        self.loginEdit.setText("")
        self.loginEdit.setObjectName("loginEdit")
        self.passwordEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.passwordEdit.setGeometry(QtCore.QRect(180, 320, 171, 30))
        self.passwordEdit.setText("")
        self.passwordEdit.setObjectName("passwordEdit")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(70, 260, 67, 22))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(70, 320, 67, 22))
        self.label_3.setObjectName("label_3")
        self.addAdminButton = QtWidgets.QPushButton(parent=Dialog)
        self.addAdminButton.setGeometry(QtCore.QRect(210, 390, 111, 30))
        self.addAdminButton.setObjectName("addAdminButton")
        self.surnameEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.surnameEdit.setGeometry(QtCore.QRect(180, 200, 171, 30))
        self.surnameEdit.setObjectName("surnameEdit")
        self.nameEdit = QtWidgets.QLineEdit(parent=Dialog)
        self.nameEdit.setGeometry(QtCore.QRect(180, 140, 171, 30))
        self.nameEdit.setObjectName("nameEdit")
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(70, 140, 67, 22))
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(70, 200, 67, 22))
        self.label_4.setObjectName("label_4")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.addAdminLabel.setText(_translate("Dialog", "Название"))
        self.label_2.setText(_translate("Dialog", "Логин"))
        self.label_3.setText(_translate("Dialog", "Пароль"))
        self.addAdminButton.setText(_translate("Dialog", "Добавить"))
        self.label.setText(_translate("Dialog", "Имя"))
        self.label_4.setText(_translate("Dialog", "Фамилия"))
