# Form implementation generated from reading ui file 'clients.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_ClientsWindow(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(508, 485)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(200, 20, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(17)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.tableWidget = QtWidgets.QTableWidget(parent=Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(30, 90, 441, 261))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.addButton = QtWidgets.QPushButton(parent=Dialog)
        self.addButton.setGeometry(QtCore.QRect(30, 370, 151, 30))
        self.addButton.setObjectName("addButton")
        self.changeButton = QtWidgets.QPushButton(parent=Dialog)
        self.changeButton.setGeometry(QtCore.QRect(180, 370, 151, 30))
        self.changeButton.setObjectName("changeButton")
        self.deleteButton = QtWidgets.QPushButton(parent=Dialog)
        self.deleteButton.setGeometry(QtCore.QRect(330, 370, 141, 30))
        self.deleteButton.setObjectName("deleteButton")
        self.backButton = QtWidgets.QPushButton(parent=Dialog, text="назад")
        self.backButton.setGeometry(QtCore.QRect(200, 450, 50, 25))
        self.backButton.setObjectName("backButton")
        self.exportButton = QtWidgets.QPushButton(
            parent=Dialog, text="экспортировать"
        )
        self.exportButton.setGeometry(QtCore.QRect(350, 450, 120, 25))
        self.exportButton.setObjectName("exportButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Клиенты"))
        self.addButton.setText(_translate("Dialog", "Добавить"))
        self.changeButton.setText(_translate("Dialog", "Редактировать"))
        self.deleteButton.setText(_translate("Dialog", "Удалить"))
