# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MenuWindow(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(508, 485)
        self.menuLabel = QtWidgets.QLabel(parent=Dialog)
        self.menuLabel.setGeometry(QtCore.QRect(130, 30, 301, 51))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(18)
        self.menuLabel.setFont(font)
        self.menuLabel.setObjectName("menuLabel")
        self.clientsButton = QtWidgets.QPushButton(parent=Dialog)
        self.clientsButton.setGeometry(QtCore.QRect(120, 130, 261, 30))
        self.clientsButton.setObjectName("clientsButton")
        self.memebershipsButton = QtWidgets.QPushButton(parent=Dialog)
        self.memebershipsButton.setGeometry(QtCore.QRect(120, 190, 261, 30))
        self.memebershipsButton.setObjectName("memebershipsButton")
        self.workoutsButton = QtWidgets.QPushButton(parent=Dialog)
        self.workoutsButton.setGeometry(QtCore.QRect(120, 250, 261, 30))
        self.workoutsButton.setObjectName("workoutsButton")
        self.exitButton = QtWidgets.QPushButton(parent=Dialog)
        self.exitButton.setGeometry(QtCore.QRect(120, 310, 261, 30))
        self.exitButton.setObjectName("exitButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.menuLabel.setText(_translate("Dialog", "Панель управления"))
        self.clientsButton.setText(_translate("Dialog", "Клиенты"))
        self.memebershipsButton.setText(_translate("Dialog", "Абонементы"))
        self.workoutsButton.setText(_translate("Dialog", "Тренировки"))
        self.exitButton.setText(_translate("Dialog", "Выйти"))
