# Form implementation generated from reading ui file 'ui/memberships.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MembershipsDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 500)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(170, 40, 231, 22))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.membershipTableWidget = QtWidgets.QTableWidget(parent=Dialog)
        self.membershipTableWidget.setGeometry(QtCore.QRect(10, 110, 481, 261))
        self.membershipTableWidget.setObjectName("membershipTableWidget")
        self.membershipTableWidget.setColumnCount(0)
        self.membershipTableWidget.setRowCount(0)
        self.backButton = QtWidgets.QPushButton(parent=Dialog)
        self.backButton.setGeometry(QtCore.QRect(10, 460, 91, 30))
        self.backButton.setObjectName("backButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Абонементы"))
        self.backButton.setText(_translate("Dialog", "Назад"))
