# Form implementation generated from reading ui file 'workouts.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WorkoutDialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(500, 500)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(180, 30, 291, 22))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(16)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.listWidget = QtWidgets.QListWidget(parent=Dialog)
        self.listWidget.setGeometry(QtCore.QRect(10, 100, 481, 241))
        self.listWidget.setObjectName("listWidget")
        self.backButton = QtWidgets.QPushButton(parent=Dialog)
        self.backButton.setGeometry(QtCore.QRect(10, 460, 51, 30))
        self.backButton.setObjectName("backButton")
        self.addWorkoutButton = QtWidgets.QPushButton(parent=Dialog)
        self.addWorkoutButton.setGeometry(QtCore.QRect(100, 350, 91, 30))
        self.addWorkoutButton.setObjectName("addWorkoutButton")
        self.changeWorkoutButton = QtWidgets.QPushButton(parent=Dialog)
        self.changeWorkoutButton.setGeometry(QtCore.QRect(200, 350, 91, 30))
        self.changeWorkoutButton.setObjectName("changeWorkoutButton")
        self.deleteWorkoutButton = QtWidgets.QPushButton(parent=Dialog)
        self.deleteWorkoutButton.setGeometry(QtCore.QRect(300, 350, 91, 30))
        self.deleteWorkoutButton.setObjectName("deleteWorkoutButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Тренировки"))
        self.backButton.setText(_translate("Dialog", "Назад"))
        self.addWorkoutButton.setText(_translate("Dialog", "Добавить"))
        self.changeWorkoutButton.setText(_translate("Dialog", "Изменить"))
        self.deleteWorkoutButton.setText(_translate("Dialog", "Удалить"))
